baseURL = 'https://espi.dev/'
languageCode = 'en-us'
title = 'espidev'
theme = ["github.com/espidev/hugo-theme-mini"]

[params]
    enableComments = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Enable tags.
[taxonomies]
   tag = "tags"

[sitemap]
changeFreq = ""  # Default change frequency (empty string)
filename = "sitemap.xml"  # Sitemap file name
priority = -1  # Default priority (-1 means omitted from rendered sitemap)
